FROM mysql as builder

RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=upajundiai
ENV MYSQL_USER=thiago
ENV MYSQL_PASSWORD=teste.123

COPY all_db.sql /docker-entrypoint-initdb.d/

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]

FROM mysql

COPY --from=builder /initialized-db /var/lib/mysql