version: '3.1'
services: 
  upadb:
    image: mysql
    container_name: upadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devel.123
      MYSQL_DATABASE: upajundiai
      MYSQL_USER: thiago
      MYSQL_PASSWORD: teste.123
    ports:
      - "3306:3306"
    networks: 
      - upanet
  
  frontend:
    image: frontend
    container_name: upafrontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80/tcp"
    networks: 
      - upanet
    depends_on: 
      - "backend"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: upabackend
    ports:
      - "8089:8089"
    networks: 
      - upanet
    depends_on:
      - "upadb"
  
networks: 
  upanet:
    name: upanet
    driver: bridge