micronaut:
  application:
    name: pacientes
  server:
    port: 8089
#  security:
#    authentication: bearer
#    token:
#      jwt:
#        signatures:
#          secret:
#            generator:
#              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
#  session:
#    http:
#      cookie: true
#      header: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/upajundiai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: devel.123
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
